// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAna0KaLENerqdsdRAXBSZnR0yoAaqcICg',
    appId: '1:1021067098206:web:ad1085a717e703c02a5ccf',
    messagingSenderId: '1021067098206',
    projectId: 'proyecto-titulo-prototipo-app',
    authDomain: 'proyecto-titulo-prototipo-app.firebaseapp.com',
    databaseURL: 'https://proyecto-titulo-prototipo-app-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-titulo-prototipo-app.appspot.com',
    measurementId: 'G-DGCYVK0DT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0XCXwdEewynd7bbRBRmYKeJMptUKZY3E',
    appId: '1:1021067098206:android:89c1406e1e3ca3c92a5ccf',
    messagingSenderId: '1021067098206',
    projectId: 'proyecto-titulo-prototipo-app',
    databaseURL: 'https://proyecto-titulo-prototipo-app-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-titulo-prototipo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Oow2V-djmbSve-eI_hIPw19bUU2tr1Y',
    appId: '1:1021067098206:ios:b1060fc789e9f6022a5ccf',
    messagingSenderId: '1021067098206',
    projectId: 'proyecto-titulo-prototipo-app',
    databaseURL: 'https://proyecto-titulo-prototipo-app-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-titulo-prototipo-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Oow2V-djmbSve-eI_hIPw19bUU2tr1Y',
    appId: '1:1021067098206:ios:7383e03bcf6951c52a5ccf',
    messagingSenderId: '1021067098206',
    projectId: 'proyecto-titulo-prototipo-app',
    databaseURL: 'https://proyecto-titulo-prototipo-app-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-titulo-prototipo-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
